version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: slackbot
      POSTGRES_USER: mic
      POSTGRES_PASSWORD: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    

    # image: python:3.8-slim
    # volumes:
    #   - ./app:/usr/src/app
    # working_dir: /usr/src/app
    # command: python main.py
    # depends_on:
    #   - postgres

volumes:
  postgres-data: